In [ ]:
import pandas as pd

In [2]:
df = pd.read_csv("F:\OneDrive\psl-data-analysis\data\psl_matches.csv")

In [3]:
df.head()

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,extras,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed
0,1416472,2023/24,2024-02-17,"Gaddafi Stadium, Lahore",1,1.5,Lahore Qalandars,Islamabad United,Sahibzada Farhan,Fakhar Zaman,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1416472,2023/24,2024-02-17,"Gaddafi Stadium, Lahore",1,1.6,Lahore Qalandars,Islamabad United,Sahibzada Farhan,Fakhar Zaman,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1416472,2023/24,2024-02-17,"Gaddafi Stadium, Lahore",1,2.1,Lahore Qalandars,Islamabad United,Fakhar Zaman,Sahibzada Farhan,...,5,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1416472,2023/24,2024-02-17,"Gaddafi Stadium, Lahore",1,2.2,Lahore Qalandars,Islamabad United,Fakhar Zaman,Sahibzada Farhan,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1416472,2023/24,2024-02-17,"Gaddafi Stadium, Lahore",1,2.3,Lahore Qalandars,Islamabad United,Sahibzada Farhan,Fakhar Zaman,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7795 entries, 0 to 7794
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   match_id                7795 non-null   int64
 1   season                  7795 non-null   str
 2   start_date              7795 non-null   str
 3   venue                   7795 non-null   str
 4   innings                 7795 non-null   int64
 5   ball                    7795 non-null   float64
 6   batting_team            7795 non-null   str
 7   bowling_team            7795 non-null   str
 8   striker                 7795 non-null   str
 9   non_striker             7795 non-null   str
 10  bowler                  7795 non-null   str
 11  runs_off_bat            7795 non-null   int64
 12  extras                  7795 non-null   int64
 13  wides                   288 non-null    float64
 14  noballs                 23 non-null     float64
 15  byes                    16 non-null     float64
 16  legbyes                 136 non-null    float64
 17  penalty                 1 non-null      float64
 18  wicket_type             403 non-null    str
 19  player_dismissed        403 non-null    str
 20  other_wicket_type       0 non-null      float64
 21  other_player_dismissed  0 non-null      float64
dtypes: float64(8), int64(4), str(10)
memory usage: 1.3 MB

In [5]:
df.describe()

,match_id,innings,ball,runs_off_bat,extras,wides,noballs,byes,legbyes,penalty,other_wicket_type,other_player_dismissed
count,7.795000e+03,7795.000000,7795.000000,7795.000000,7795.000000,288.000000,23.0,16.000000,136.000000,1.0,0.0,0.0
mean,1.416488e+06,1.489416,9.695548,1.322001,0.075690,1.229167,1.0,2.250000,1.264706,5.0,NaN,NaN
std,1.011414e+01,0.499920,5.694842,1.650024,0.367276,0.828236,0.0,1.437591,0.800327,NaN,NaN,NaN
min,1.416472e+06,1.000000,0.100000,0.000000,0.000000,1.000000,1.0,1.000000,1.000000,5.0,NaN,NaN
25%,1.416479e+06,1.000000,4.600000,0.000000,0.000000,1.000000,1.0,1.000000,1.000000,5.0,NaN,NaN
50%,1.416487e+06,1.000000,9.600000,1.000000,0.000000,1.000000,1.0,1.500000,1.000000,5.0,NaN,NaN
75%,1.416497e+06,2.000000,14.500000,1.000000,0.000000,1.000000,1.0,4.000000,1.000000,5.0,NaN,NaN
max,1.416505e+06,2.000000,19.900000,6.000000,5.000000,5.000000,1.0,4.000000,4.000000,5.0,NaN,NaN